services:

  postgres:
    image: postgres:alpine

    environment:
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=notesplace

    ports:
      - 5432:5432

    env_file:
      - .env

    volumes:
      - ./db-data/:/var/lib/postgresql/data/

  notesplace:
    build:
      dockerfile: Dockerfile
      context: .
    
    command: app
    
    ports:
      - 8080:8080

    environment:
      - GIN_MODE=release
      - DB_HOST=postgres

    env_file:
      - .env

    depends_on:
      - postgres