networks:
  app-internal:
    internal: true
  app-external:

services:
  postgres:
    image: postgres:alpine

    env_file:
      - ".env"

    environment:
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=notesplace

    volumes:
      - ./db-data/:/var/lib/postgresql/data/
    networks:
      - app-internal

  notesplace:
    build:
      dockerfile: Dockerfile
      context: .

    env_file:
      - ".env"

    ports:
      - 8080:8080

    environment:
      - GIN_MODE=release
      - DB_HOST=postgres
      - DB_PASSWORD=secret

    depends_on:
      - postgres
    networks:
      - app-internal

    restart: on-failure
  web:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    networks:
      - app-internal
      - app-external
