services:
  postgres:
    image: postgres:alpine

    env_file:
      - ".env"

    environment:
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=notesplace

    ports:
      - 5432:5432

    volumes:
      - ./db-data/:/var/lib/postgresql/data/

  notesplace:
    build:
      dockerfile: Dockerfile
      context: .

    env_file:
      - ".env"

    ports:
      - 8080:8080

    environment:
      - GIN_MODE=release
      - DB_HOST=postgres
      - DB_PASSWORD=secret

    depends_on:
      - postgres

    restart: on-failure
