FROM node:20-alpine AS build
WORKDIR /app
COPY ./web/package*.json ./
RUN npm install
COPY ./web .
RUN npm run build

FROM nginx:mainline-alpine AS serve

WORKDIR /html
COPY --from=build /app/build .
