package model

import "time"

// Notebook Model
type Notebook struct {
	// The notebook ID.
	//
	// Required. Expected to be a string generated by Yeast. (db: SERIAL)
	ID string `json:"id"`
	// Name of the notebook
	//
	// Optional.
	Name string `json:"name"`
	// Password to gain privileged access to the notebook.
	//
	// Optional. Encoded.
	Password string `json:"-"`
	// Protection level.
	//
	// Enum - possible values: "none" | "readonly" | "protected" (0 | 1 | 2) (db: enum)
	//
	// None | 0 - everyone has access
	//
	// ReadOnly | 1 - read only. password needed to write
	//
	// Protected | 2 - protected. password needed to read
	//
	// Required.
	ProtectionLevel uint8 `json:"protection_level"`
	// Created at timestamp.
	//
	// Required.
	CreatedAt time.Time `json:"created_at"`
	// Updated at timestamp.
	//
	// Required.
	UpdatedAt time.Time `json:"updated_at"`
}
